version: "3.5"

services:
  server:
    image: cortezaproject/corteza:${SOFTWARE_VERSION_TAG}
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "172.17.0.1:18080:80"
    volumes:
      - ./storage:/data

  db:
    image: elestio/postgres:15
    restart: always
    healthcheck:
      {
        test: ["CMD-SHELL", "pg_isready -U postgres"],
        interval: 10s,
        timeout: 5s,
        retries: 5,
      }
    ports:
      - 172.17.0.1:4921:5432
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: corteza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:41210:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
